name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ejecutar solo en la rama principal
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u andrealiznm --password-stdin

      - name: Build Docker image
        run: docker build . -t ghcr.io/andrealiznm/calculadora:latest

      - name: Push Docker image
        run: docker push ghcr.io/andrealiznm/calculadora:latest
        
  deploy:
    needs: build  # Ejecutar después de la construcción
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials alculadora-cluster-1 --zone us-central1 --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
