name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ejecutar solo en la rama principal
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u andrealiznm --password-stdin

      - name: Build Docker image
        run: docker build . -t ghcr.io/andrealiznm/calculadora:latest

      - name: Push Docker image
        run: docker push ghcr.io/andrealiznm/calculadora:latest
        
  deploy:
    needs: build  # Ejecutar después de la construcción
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Autenticarse en Google Cloud
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }} # El secreto que contiene tu clave de cuenta de servicio
          project_id: masterdevsecops

      - name: Install gke-gcloud-auth-plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Get GKE credentials
        run: |
          gcloud auth activate-service-account --key-file="${{ secrets.GCP_SA_KEY }}"
          gcloud container clusters get-credentials calculadora-cluster-1 --region us-central1 --project masterdevsecops

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/calculadora calculadora=ghcr.io/andrealiznm/calculadora:latest
          kubectl rollout status deployment/calculadora
          
