name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ejecutar solo en la rama principal
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u andrealiznm --password-stdin

      - name: Build Docker image
        run: docker build . -t ghcr.io/andrealiznm/calculadora:latest

      - name: Push Docker image
        run: docker push ghcr.io/andrealiznm/calculadora:latest
        
  deploy:
    needs: build  # Ejecutar después de la construcción
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. Autenticarse en Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # Agregar la clave del Service Account

      # 3. Configurar kubectl para GKE
      - name: Set up GKE Cluster
        run: |
          gcloud container clusters get-credentials calculadora-cluster-1 --region us-central1 --project masterdevsecops

      # 4. Desplegar la aplicación en Kubernetes
      - name: Deploy to GKE
        run: |
          kubectl set image deployment/calculadora calculadora=ghcr.io/${{ github.repository }}:latest
